### ISSUE TITLE
validate texts

### ISSUE THREAD

**Issue by roannav** [jeffrey-zang/sands-of-typing#14]
Hi [@jeffrey-zang](https://github.com/jeffrey-zang),

Many people are contributing new texts.

I would like to write a validate_text.py script that will check all the files in lib/*.json.
For starters, it will ensure that each sample text is within the character limits:

Easy: 0-150 characters
Medium: 150-250 characters
Hard: 250+ characters 

It will print an error to console, if not within the character limits.

Please assign this issue to me.

**Comment by roannav** [comment]
[@jeffrey-zang](https://github.com/jeffrey-zang) Could we modify the ranges just a bit, so that a 150 character text will go in easy.json, but not medium.json?
Likewise, a 250 character text will go in medium.json, but not hard.json.
Should there be a max char limit on hard text?  like say 500?

**Comment by jeffrey-zang** [comment]
Modifications sound good. 500 sounds good too.
